### ISSUE TITLE
Falta el store casospositivos

### ISSUE THREAD

**Issue by fcolomas** [eCaller/eCallerEpidemiaWeb#4]
Ejecutando la version actual se nota que al intentar agregar una combinacion positiva falla el codigo:

TypeError: Cannot read property 'id' of undefined
    at VueComponent.nuevaCombinacion (triage.vue?0e94:305)
    at click (eval at ./node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-e1ce69e2","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/triage/triage.vue (app.js:4630), <anonymous>:498:46)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at HTMLButtonElement.invoker (vue.esm.js?efeb:2188)
    at HTMLButtonElement.original._wrapper (vue.esm.js?efeb:7565)

Revisando no existe un store creado para casospositivos, posiblemente la carpeta store no esta completa

**Comment by fcolomas** [comment]
Pasa con una base de datos limpia, si se intenta ingresar el triage se reproduce el caso, ingresando datos en la base el comportamiento no se reproduce

**Comment by JoseAlbertoDev** [comment]
En la siguiente subida debería estar arreglado. Faltaba una comprobación en el método nuevaCombinación.

**Comment by JoseAlbertoDev** [comment]
Ya debería estar resuelto. Actualizate desde el master y me confirmas  para cerrar el issue.

**Comment by joedayz** [comment]
Hola Jose. Me pasa, que necesitaba crear dos variables RESPUESTA_POSITIVA y RESPUESTA_NEGATIVA y cargo. Pero a la hora de crear una nueva combinación, me sale:

[Vue warn]: Computed property "casospositivos" was assigned to but it has no setter.

**Comment by joedayz** [comment]
Ok. Esto lo arreglo:

nuevaCombinacion() {
        let combinacion = {id:1, respuestas: null};
        if (this.casospositivos && this.casospositivos.length>0) {
          let orden = this.casospositivos[this.casospositivos.length-1].id + 1;
          combinacion.id=orden;
          this.casospositivos.push(combinacion);
        } else {
          **this.casospositivos.push(combinacion);**
        }
      }

**Comment by JoseAlbertoDev** [comment]
Buenas, el problema era la línea que has modificado, al usar los getters de Vuex, no se puede hacer una asignación tal que así **this.casospositivos = [combinacion]** ya que entonces se pierde toda la reactividad del objeto.

Una forma de solucionarlo es esa, o creando una mutación para setear el nuevo array que ha sido nuestra solución. Estos cambios se subirán en próximas versiones.
